        <button id="btn-0-0" class="white"></button>
        <button id="btn-0-1" class="white"></button>
        <button id="btn-0-2" class="white"></button>
        <button id="btn-0-3" class="white"></button>
        <button id="btn-0-4" class="white"></button>
        <button id="btn-0-5" class="white"></button>
        <button id="btn-0-6" class="white"></button>
        <button id="btn-0-7" class="white"></button>
        <button id="btn-0-8" class="white"></button>
        <button id="btn-0-9" class="white"></button>
        <br>
        <button id="btn-1-0" class="white"></button>
        <button id="btn-1-1" class="white"></button>
        <button id="btn-1-2" class="white"></button>
        <button id="btn-1-3" class="white"></button>
        <button id="btn-1-4" class="white"></button>
        <button id="btn-1-5" class="white"></button>
        <button id="btn-1-6" class="white"></button>
        <button id="btn-1-7" class="white"></button>
        <button id="btn-1-8" class="white"></button>
        <button id="btn-1-9" class="white"></button>
        <br>
        <button id="btn-2-0" class="white"></button>
        <button id="btn-2-1" class="white"></button>
        <button id="btn-2-2" class="white"></button>
        <button id="btn-2-3" class="white"></button>
        <button id="btn-2-4" class="white"></button>
        <button id="btn-2-5" class="white"></button>
        <button id="btn-2-6" class="white"></button>
        <button id="btn-2-7" class="white"></button>
        <button id="btn-2-8" class="white"></button>
        <button id="btn-2-9" class="white"></button>
        <br>
        <button id="btn-3-0" class="white"></button>
        <button id="btn-3-1" class="white"></button>
        <button id="btn-3-2" class="white"></button>
        <button id="btn-3-3" class="white"></button>
        <button id="btn-3-4" class="white"></button>
        <button id="btn-3-5" class="white"></button>
        <button id="btn-3-6" class="white"></button>
        <button id="btn-3-7" class="white"></button>
        <button id="btn-3-8" class="white"></button>
        <button id="btn-3-9" class="white"></button>
        <br>
        <button id="btn-4-0" class="white"></button>
        <button id="btn-4-1" class="white"></button>
        <button id="btn-4-2" class="white"></button>
        <button id="btn-4-3" class="white"></button>
        <button id="btn-4-4" class="white"></button>
        <button id="btn-4-5" class="white"></button>
        <button id="btn-4-6" class="white"></button>
        <button id="btn-4-7" class="white"></button>
        <button id="btn-4-8" class="white"></button>
        <button id="btn-4-9" class="white"></button>
        <br>
        <button id="btn-5-0" class="white"></button>
        <button id="btn-5-1" class="white"></button>
        <button id="btn-5-2" class="white"></button>
        <button id="btn-5-3" class="white"></button>
        <button id="btn-5-4" class="white"></button>
        <button id="btn-5-5" class="white"></button>
        <button id="btn-5-6" class="white"></button>
        <button id="btn-5-7" class="white"></button>
        <button id="btn-5-8" class="white"></button>
        <button id="btn-5-9" class="white"></button>
        <br>
        <button id="btn-6-0" class="white"></button>
        <button id="btn-6-1" class="white"></button>
        <button id="btn-6-2" class="white"></button>
        <button id="btn-6-3" class="white"></button>
        <button id="btn-6-4" class="white"></button>
        <button id="btn-6-5" class="white"></button>
        <button id="btn-6-6" class="white"></button>
        <button id="btn-6-7" class="white"></button>
        <button id="btn-6-8" class="white"></button>
        <button id="btn-6-9" class="white"></button>
        <br>
        <button id="btn-7-0" class="white"></button>
        <button id="btn-7-1" class="white"></button>
        <button id="btn-7-2" class="white"></button>
        <button id="btn-7-3" class="white"></button>
        <button id="btn-7-4" class="white"></button>
        <button id="btn-7-5" class="white"></button>
        <button id="btn-7-6" class="white"></button>
        <button id="btn-7-7" class="white"></button>
        <button id="btn-7-8" class="white"></button>
        <button id="btn-7-9" class="white"></button>
        <br>
        <button id="btn-8-0" class="white"></button>
        <button id="btn-8-1" class="white"></button>
        <button id="btn-8-2" class="white"></button>
        <button id="btn-8-3" class="white"></button>
        <button id="btn-8-4" class="white"></button>
        <button id="btn-8-5" class="white"></button>
        <button id="btn-8-6" class="white"></button>
        <button id="btn-8-7" class="white"></button>
        <button id="btn-8-8" class="white"></button>
        <button id="btn-8-9" class="white"></button>
        <br>
        <button id="btn-9-0" class="white"></button>
        <button id="btn-9-1" class="white"></button>
        <button id="btn-9-2" class="white"></button>
        <button id="btn-9-3" class="white"></button>
        <button id="btn-9-4" class="white"></button>
        <button id="btn-9-5" class="white"></button>
        <button id="btn-9-6" class="white"></button>
        <button id="btn-9-7" class="white"></button>
        <button id="btn-9-8" class="white"></button>
        <button id="btn-9-9" class="white"></button>
        <br>